debug: false
server:
  port: 8080
  context-path: /demo
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: null
mybatis:
  config-location: classpath:/config/mybatis-config.xml
  mapper-locations:
  - classpath:/mapper/*.xml
  - classpath:/dao/*.xml