# 我是开发环境
debug: true
server:
  port: 8080
  context-path: /monolith
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.77.181.175:3306/web?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: mysql123456
  redis:
    database: 0
    host: 120.77.181.175
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  thymeleaf:
    mode: HTML
    cache: false
mybatis:
  config-location: classpath:/config/mybatis-config.xml
  mapper-locations:
  - classpath:/mapper/*.xml
  - classpath:/dao/*.xml
flyway:
  enabled: false